---
- hosts: localhost
  become: yes
  become_method: sudo
  tasks:
  - name: Starting minikube as root with vm-driver {{ minikube_vm_driver }}...
    command:
      argv:
        - "{{ minikube_install_dir }}/minikube"
        - "--vm-driver={{ minikube_vm_driver | default(none) }}"
        - start
